### ISSUE TITLE
S2 - Hacer la vista de marketplace

### ISSUE THREAD

**Issue by Khrisefzm** [Khrisefzm/BacanMarketPlace#18]
Como usuario debo poder ver todos los productos que están a la venta y los productos que puedo intercambiar.

**Criterios de aceptación**
- [x] Tiene que diferenciarse dos categorías: Productos vendidos y productos de intercambio
- [x] Se tiene que ver el precio del producto o algunos productos que se piden para el intercambio.
- [x] Tiene que poder hacerse clic en la tarjeta del producto para ver los detalles.

**Comment by brianmoyar89** [comment]
Estructura Principal Terminada, falta vincular la base de datos con la vista.
