### ISSUE TITLE
S2 - Hacer la base de datos de Productos vendidos (seller_products)

### ISSUE THREAD

**Issue by Khrisefzm** [Khrisefzm/BacanMarketPlace#23]
Como desarrollador necesito tener una base de datos para obtener u enviar información.

**Criterios de aceptación:**
- [ ] Se debe tener como PK a seller_product_id
- [ ] Se debe guardar el tipo de producto (product_type)
- [ ] Se debe guardar el nombre del autor (autor) solo si es un libro, caso contrario null.
- [ ] Se debe guardar la categoria del producto (category)
- [ ] Se debe guardar la descripción del producto (description)
- [ ] Se debe guardar el precio del producto.

**Comment by DanielNunez04** [comment]
Se hace la tabla "seller_products"
